repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.770'
    hooks:
    - id: mypy
      additional_dependencies: [ruamel.yaml,toml,msgpack]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: mixed-line-ending
    - id: trailing-whitespace
    - id: requirements-txt-fixer
    - id: fix-encoding-pragma
    - id: check-byte-order-marker
    - id: debug-statements
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
